### ISSUE TITLE
TODO (UI/UX/Other Frontend)

### ISSUE THREAD

**Issue by Alixandria** [Alixandria/Navigator#1]
- [ ] Make a basic config menu
- [ ] Import/Export map flags?
- [ ] Custom "nicknames" for map flags, or otherwise being able to add notes on them
- [ ] Decide on styling/branding(?)
- [ ] lmao learn imgui
