### ISSUE TITLE
TODO (UI/UX)

### ISSUE THREAD

**Issue by Alixandria** [Alixandria/Navigator#1]
In no particular order

- [ ] Make a basic config menu that actually works
- [ ] Ideally decide on a maximum amount of map flags to be stores (optional? TBD)
- [ ] Import/Export map flags?
- [ ] IPC?
- [ ] Custom nicknames for map flags (ideally short)
- [ ] Optional extended description/notes for a given flag
