### ISSUE TITLE
TODO (Backend)

### ISSUE THREAD

**Issue by Alixandria** [Alixandria/Navigator#2]
In no particular order

- [ ] Yoink the required sigs for placing/retrieving map flags
- [ ] Figure out a decent way to store flags
- [ ] As mentioned in #1, IPC? If so, what would be reasonable to mess with? 
- [ ] No instances except Eureka, Bozja, or other Large-Scale content that may be added in future patches for safety. Otherwise, overworld zones only.
